### ISSUE TITLE
No pie.freq function in fastBCR

### ISSUE THREAD

**Issue by sheenaseven** [ZhangLabTJU/fastBCR#1]
Dear authors,

After installing fastBCR, I ran the example, but the following functions (pie.freq, junc.len, msa.tree) were not found:
<img width="433" alt="image" src="https://github.com/ZhangLabTJU/fastBCR/assets/37868618/b7fc78d6-24a4-4fc0-bf45-2177fb5aa999">
Could you please help to verify the existence of the built-in functions? Have the names of these functions been changed?

Best regards,
Sheena

**Comment by ZhangLabTJU** [comment]
Dear Sheena,

As you mentioned, the names of these functions have changed. We are currently improving our R package, and these functions will be further updated, with some new functions being introduced. For now, you can use the previous version (https://zenodo.org/record/8320531) for testing and data analysis. We will notify you promptly when the updated version is available.

Yours Sincerely,
Kaixuan, Wang

**Comment by sheenaseven** [comment]
Dear Kaixuan,

Great thanks for your quick reply! 

Best regards,
Sheena

**Comment by ZhangLabTJU** [comment]
Dear Sheena,

We have completed the updated version of fastBCR (v1.1). The latest paper **Protocol for fast clonal family inference and analysis from large-scale B cell receptor repertoire sequencing data.** (https://doi.org/10.1016/j.xpro.2024.102969) has been published online today on _STAR Protocols_. We also provide a R Markdown file (fastBCR_pipeline.Rmd) with reproducible results in the "/example" folder. We hereby inform you of this matter and hope our method can be of assistance to you. If you have any questions, please do not hesitate to contact us! 

Yours Sincerely,
Kaixuan, Wang
